### ISSUE TITLE
Uncaught TypeError: Cannot set property 'version' of undefined

### ISSUE THREAD

**Issue by tobias-f** [cheminfo/openchemlib-js#10]
Hello.

I just cloned the repository and built it with gulp. Including the resulting lib.js throws an exception @ line 850 ``toReturn.version = '3.0.0-alpha5';``
Basically, the line before ``var toReturn = $wnd["actchem"];`` returns an undefined.

The lib.js file that is currently in the repo works just fine, but is missing some of the newer features :-)

Any clue what's the problem?

Thanks....

Best,

Tobias

**Comment by targos** [comment]
Hello,

Thank you for your interest.
We are aware that the build doesn't work anymore. A lot of classes have changed in 1bc1cd14928889f4c0f66970b76fbbb3cefab195 and we are currently working on integrating everything again

**Comment by rufenerc** [comment]
I've resolved the issue.
