### ISSUE TITLE
Steroechemistry not always being read from molfile

### ISSUE THREAD

**Issue by tdudgeon** [cheminfo/openchemlib-js#103]
I'm finding that when reading a 3D molfile the stereochemistry is not always being read, so that, for instance, if the molecule is written as isomeric smiles the stereo is lost. This seems to be molecule dependent. Some molecules retain the stereo, some loose it.

Here is an example where it happens:
https://codesandbox.io/s/reverent-noyce-8koqj?file=/src/index.js

Is this something I'm doing wrong, or is it a problem with openchemlib js?

**Comment by targos** [comment]
@lpatiny @thsa

**Comment by lpatiny** [comment]
You should specify in the molfile count line that this molecule is chiral and not recemate

![image](https://user-images.githubusercontent.com/1484241/87284426-a526be00-c4f6-11ea-81cb-a5949e6defe0.png)


![image](https://user-images.githubusercontent.com/1484241/87284277-79a3d380-c4f6-11ea-889c-7cab012595b3.png)
