### ISSUE TITLE
OpenChemLib fail to render this SMILES

### ISSUE THREAD

**Issue by kuige** [cheminfo/openchemlib-js#105]
COc1ccccc1-n1cnn(C[NH+]2CCCC[C@H]2Cn2ccnc2)S1

<img width="415" alt="image" src="https://user-images.githubusercontent.com/8212800/88900926-b3a8ff80-d282-11ea-8aa0-4fce5e410266.png">

**Comment by lpatiny** [comment]
Are you sure about the smiles ?

You describe an aromatic ring that does not contain only lowercases.

`n1cnnS1`

`COc1ccccc1-n1cnn(C[NH+]2CCCC[C@H]2Cn2ccnc2)s1` renders even if I'm not certain it is the molecule you want.

**Comment by kuige** [comment]
I tried marvinjs, it renders `COc1ccccc1-n1cnn(C[NH+]2CCCC[C@H]2Cn2ccnc2)S1` like this:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/8212800/88995769-1f8c7600-d31e-11ea-9151-f9c465128d0d.png">

It seems that OpenChemLib is Intolerable about any mistakes, more strict than others.

`COc1ccccc1-n1cnn(C[NH+]2CCCC[C@H]2Cn2ccnc2)s1` is the molecule I want.

Thanks lpatiny.
