### ISSUE TITLE
emulate GlyphVector

### ISSUE THREAD

**Issue by targos** [cheminfo/openchemlib-js#11]
the method `protected float getStringWidth(String theString)` in the latest SVGDepictor uses the GlyphVector class from awt. Compilation is impossible until we emulate it

**Comment by rufenerc** [comment]
Added just dummy class, so it compiles

**Comment by rufenerc** [comment]
If we want to use it, we need to add proper measuring with the font stuff

**Comment by rufenerc** [comment]
Sorry I broke the build with this

**Comment by rufenerc** [comment]
No longer needed: Font measuring via        currentFont.getStringBounds(theString,graphics.getFontRenderContext()).getWidth();
