### ISSUE TITLE
v7.3.0 release: JS assets are missing

### ISSUE THREAD

**Issue by flange-ipb** [cheminfo/openchemlib-js#110]
Hello, could you please add the JS assets to the [7.3.0 release](https://github.com/cheminfo/openchemlib-js/releases/tag/v7.3.0). I prefer to download them directly instead of using npm. Thanks!

**Comment by targos** [comment]
Hello, unfortunately our new release tooling does not upload assets to GitHub anymore.
You can access them from other sources though:
- Our CDN: https://www.lactame.com/lib/openchemlib/7.3.0/
- Third parties like unpkg that expose the contents of npm packages: https://unpkg.com/browse/openchemlib@7.3.0/dist/

**Comment by flange-ipb** [comment]
Alright, thanks for the links. Please note that the sha256sum of openchemlib-full.js from your CDN does not match the one in the npm repo.

**Comment by targos** [comment]
This is expected. The files are generated by different workflows and contain a header with the generation time, which is different.
