### ISSUE TITLE
svg is not shown

### ISSUE THREAD

**Issue by worldresize** [cheminfo/openchemlib-js#115]
idcode:O=C(O)C(N)CC(C)C

when i want to show this svg, the page is slow and not working.

**Comment by lpatiny** [comment]
Can you provide a link to your code ?

**Comment by worldresize** [comment]
Thanks!I have solved. I had the smiles info so i used the fromSmiles function instead of fromIDCode!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cheminfo/openchemlib-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 晚上11:50
***@***.***&gt;;
抄送:&nbsp;"Bruce ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cheminfo/openchemlib-js] svg is not shown (#115)





 
Can you provide a link to your code ?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
