### ISSUE TITLE
[Question]: Is it possible to generate a 3d static image?

### ISSUE THREAD

**Issue by bylethviva** [cheminfo/openchemlib-js#118]
Is there any way to generate a static 3d image of a chemical structure from its smile code or similar? Maybe there's something similar to `Molecule.toSVG` that I've missed somewhere? Thank you!

**Comment by targos** [comment]
Unfortunately, there is no way to generate a 3D image with this library.
You can use the [ConformerGenerator](https://cheminfo.github.io/openchemlib-js/classes/ConformerGenerator.html) to generate 3D coordinates, export the molecule as a Molfile and display it with one of the existing librairies that support it.

**Comment by bylethviva** [comment]
@targos thank you for that information. Do you have any libraries for 3d image generation that you could recommend?
