### ISSUE TITLE
possibility to add diastereotopic ID in svg

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#12]
var prefix="ABC";
var molecule=ACT.Molecule.fromMolfile(value.get());
var svg=molecule.toSVG(300,200,prefix);

var regexp=RegExp("("+prefix+":Atom:)([0-9]+)\"","g");
var ids=molecule.getDiastereotopicAtomIDsArray();

svg=svg.replace(regexp, function(match, p1, p2) {
    return p1+p2+'" data-atomid="'+ids[p2<<0]+'"';
});

**Comment by targos** [comment]
moved to ocl extended
