### ISSUE TITLE
The functionality of the atoms in the tools panels is inconsistent

### ISSUE THREAD

**Issue by NRayya** [cheminfo/openchemlib-js#138]
I think that in the tools panels, the hydrogen atom should have a different effect. As carbon results in CH4, and Nitrogen in NH3.., I think H should result in H2 when applied in space.

**Comment by targos** [comment]
This repository is only about porting the Java library to JS. Please open general functionality and bug tickets in https://github.com/Actelion/openchemlib/issues

**Comment by NRayya** [comment]
Thanks
