### ISSUE TITLE
one tool is not clickable 

### ISSUE THREAD

**Issue by NRayya** [cheminfo/openchemlib-js#139]
The following tool is not clickable.

![tool](https://user-images.githubusercontent.com/82588017/194891513-aed6bec8-653a-41bf-ab76-489485e78489.png)

**Comment by NRayya** [comment]
Text button is also not clickable

![text](https://user-images.githubusercontent.com/82588017/194894656-95e8c50d-58ac-46ac-8b77-4bd72818e8ad.png)

**Comment by targos** [comment]
These tools are only available in some circumstances. See https://openmolecules.org/editor/editor.html (bottom of the page).
