### ISSUE TITLE
rename actchem to OCL ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#14]
Currently in the window the library is called using window.actchem

I think it would make sense to export OCL for OpenChemLib ?

**Comment by targos** [comment]
I agree. @rufenerc ?

**Comment by rufenerc** [comment]
Will do it on next release

**Comment by rufenerc** [comment]
Should it be OCL or ocl?

**Comment by lpatiny** [comment]
OCL

**Comment by targos** [comment]
fixed in 75277f2b5e784836c480d81632378c606f4722f0
