### ISSUE TITLE
Constants in JSMolecule

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#148]
Many constants from 'Molecule' have changed of values and also new constants are available.

https://github.com/cheminfo/openchemlib-js/blob/268a617c80e7106bf9cef18304df085c5aabfd8f/src/com/actelion/research/gwt/chemlib/com/actelion/research/chem/Molecule.java#L145-L163

@targos :    
- May I just copy paste them from Molecule.java ? (and update types.d.ts)
- How should we deal with the long in those constants ? I guess that if we are not yet using 53 bits it should be ok but some of those constants are close (47 bits already).

**Comment by targos** [comment]
I suppose you can just copy-paste, but I don't know what will happen tho the `long` values. To be tested.

**Comment by lpatiny** [comment]
Closed by https://github.com/cheminfo/openchemlib-js/commit/81d7361d6792c01ee3a9f36d01dd9bc41ab020ae
