### ISSUE TITLE
Some modifications

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#167]
Thomas asked us to make the following modifications

Could you please update these two issues manually?:

JSMoleculeProperties:

import com.actelion.research.chem.PropertyCalculator;
change to:

import com.actelion.research.chem.prediction.PropertyCalculator;

GWTGeomFactory:

import com.actelion.research.chem.ChemistryHelper;

change to:

import com.actelion.research.share.gui.ChemistryGeometryHelper;

and change the name in one source code instance further down!!!

**Comment by targos** [comment]
Done in https://github.com/cheminfo/openchemlib-js/pull/186
