### ISSUE TITLE
cannot find file ../dist/openchemlib-full.js

### ISSUE THREAD

**Issue by shiyu-wangbyte** [cheminfo/openchemlib-js#199]
hello developers:
I want to run the file in examples folder, such as ShowStructures.html,
But i cannot find the following scripts:
../dist/openchemlib-full.js
../dist/openchemlib-core.js

So, how can i find these files?

**Comment by targos** [comment]
These files are created by the build process (`npm run build`). You can also download them from here: https://www.lactame.com/lib/openchemlib/8.9.0/

**Comment by shiyu-wangbyte** [comment]
Thank you.
