### ISSUE TITLE
another method for group getDiastereotopicIDs

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#30]
Often we would like to have an array of diastereotopic IDs and the number of occurence of each of them.
It would therefore be nice if OCL.getGroupedDiastereotopicIDs exists. The code would be something like:

```
function getGroupedDiastereotopicIDs (options) {
var diaIDs=molecule.getDiastereotopicAtomIDs(options);
var diaIDsObject={};

for (var i=0; i<diaIDs.length; i++) {
    var diaID=diaIDs[i];
    if (! diaIDsObject[diaID]) {
        diaIDsObject[diaID]={
            counter:1,
            atom: [i],
            oclID: oclID
        }
    } else {
        diaIDsObject[diaID].counter++;
        diaIDsObject[diaID].atom.push(i);
    }
}

var diaIDsTable=[];
for (var key of Object.keys(diaIDsObject)) {
    diaIDsTable.push(diaIDsObject[key]);
}
return diaIDsTable;
}

```

**Comment by targos** [comment]
didn't we agree not to add javascript methods in this project ?

**Comment by lpatiny** [comment]
Then I can see 2 possibilities
* do it in java
* extend the "molecule" object in openchemlib-extended but I have no idea if there is a way to extend the molecule object ???

**Comment by targos** [comment]
Yes it can be easily extended:
```js
OCL.Molecule.prototype.printHydrogens = function(){
  console.log(this.getNumberOfHydrogens());
};
molecule.printHydrogens();
// 20
```

**Comment by lpatiny** [comment]
OK it will then be implemented in openchemlib-extended
