### ISSUE TITLE
getIDCode and canonizer options

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#39]
We would need options forthe canonizer allowing to generate the corresponding IDCode

https://github.com/Actelion/openchemlib/blob/50cef8d11ed05100d651a6d2ba702d38999fe7e4/src/main/java/com/actelion/research/chem/Canonizer.java#L46-L72

In particular I'm interested in
- ENCODE_ATOM_CUSTOM_LABELS = 8;
- ENCODE_ATOM_SELECTION = 16;

https://github.com/cheminfo/openchemlib-js/blob/bcf7b0240f7b9eb8fbe22af6b12bee3aa9f9794e/src/com/actelion/research/gwt/chemlib/com/actelion/research/chem/io/CompoundFileParser.java#L165-L167

**Comment by lpatiny** [comment]
Currently the "Canonizer" java class is not instantiable in javascript as far as I know.

To keep it simple what I suggest is that we change the javascript function:

```Molecule.getIDCode( parameter )```

if parameter is empty we just return the current code
if parameter is not empty we do

```new Canonizer(molecule, parameter).getIDCode()```

Ideally the parameter should be public static values. Currently there are 2 importants options that can be "or"
* ENCODE_ATOM_CUSTOM_LABELS
* ENCODE_ATOM_SELECTION

https://github.com/Actelion/openchemlib/blob/4715526c70a07141e7c42a98fb0919290cb51f90/src/main/java/com/actelion/research/chem/Canonizer.java#L65-L69

Should those 2 statics be at the level of OCL ?

This means we could write something like

```molecule.getIDCode(OCL.ENCODE_ATOM_CUSTOM_LABELS | OCL.ENCODE_ATOM_SELECTION)```

**Comment by targos** [comment]
This is possible like this:
```js
const flag = OCL.Molecule.CANONIZER_ENCODE_ATOM_CUSTOM_LABELS | OCL.Molecule.ENCODE_ATOM_SELECTION;
mol.getCanonizedIDCode(flag);
```

Possible flags:
```
CANONIZER_CREATE_SYMMETRY_RANK
CANONIZER_CONSIDER_DIASTEREOTOPICITY
CANONIZER_CONSIDER_ENANTIOTOPICITY
CANONIZER_CONSIDER_STEREOHETEROTOPICITY
CANONIZER_ENCODE_ATOM_CUSTOM_LABELS
CANONIZER_ENCODE_ATOM_SELECTION
CANONIZER_ASSIGN_PARITIES_TO_TETRAHEDRAL_N
CANONIZER_COORDS_ARE_3D
CANONIZER_CREATE_PSEUDO_STEREO_GROUPS
CANONIZER_DISTINGUISH_RACEMIC_OR_GROUPS
```
