### ISSUE TITLE
Make the library compatible with SpiderMonkey

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#45]
Seems windows and some other variable are not the same as in node making the library incompatible with SpiderMonkey

We would need it in order to use it in couchdb to automatically calculate idCode from molfile in a view. Like that we would be able to easily create a view for substructure search and even to create the preindex if we want. The goal being to be able to show the interactive substructure search on a set of 20000 molecules

**Comment by targos** [comment]
fixed with https://github.com/cheminfo/openchemlib-js/commit/38e1c51497f73392b9e51fa3a17bc752369a281e
