### ISSUE TITLE
Future API Change In JSMolecule

### ISSUE THREAD

**Issue by rufenerc** [cheminfo/openchemlib-js#51]
The OC Molecule class needs an additional parameter for the 
public int getElectronValenceCorrection(int atom)  method. 
Can/should it be changed in the JSMolecule API or can we stop exposing this API?

The OC  Molecule method int[] getSortedConnMap(int atom)  is now private and can no longer be exposed in JSMolecule.
Can we do this change?

**Comment by lpatiny** [comment]
We have a script that allows more or less to automatically regenerate all the public methods from the java code to the JSMolecule.
So indeed you may make the breaking change without problem.
We will still however have to tune a little bit the script, especially to deal with multiple methods that allows various types of parameter.

**Comment by targos** [comment]
Given that we are not using this API and it is not documented yet, I went ahead and made the changes. They are now in the latest release.
