### ISSUE TITLE
Possibility to select font size / bond width in SVG ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#53]
The SVG depictor use some parameters that would be nice to be able to tune (for printing label for examples)

* Font name
* Font Plain, bold, italic
* Font size
* Line width

https://github.com/Actelion/openchemlib/blob/4633da5f2bfc3fbd59e2e01897c42d7be2b22b2d/src/main/java/com/actelion/research/chem/SVGDepictor.java

Would it be possibile to allow those options in the typerenderer and the getSVG of openchemlib ?

@stropitek

**Comment by targos** [comment]
Currently the only things that can be modified are:
- font size
- line width
- color

You will have to open an issue upstream for more

**Comment by targos** [comment]
Actually nothing can be modified, as the methods are declared `protected`. I'm not sure it makes sense to change the values, they are probably modified during rendering by the depictor.

**Comment by rufenerc** [comment]
Right, the Depictor decides what size it should be. However, I guess one could think about configuring the SVGDepictor's font family and style.

**Comment by lpatiny** [comment]
It would be nice if it was possible indeed to customize the font. Also if we could get an option so that all the atoms are drawn in black it would be nice. We are generating labels with a thermal transfer printer on which we print the chemical structure and it does not support colors.

**Comment by rufenerc** [comment]
I think, the last could be handled by passing AbstractDepictor. cDModeNoImplicitAtomLabelColors as mode in the constructor of SVGDepictor(mol, mode,id) in the SVGRenderer.renderMolecule() method

**Comment by targos** [comment]
@stropitek The option is already made available for the `toSVG` method: https://github.com/cheminfo/openchemlib-js/blob/master/Documentation.md#depictor-options

**Comment by lpatiny** [comment]
Indeed to get the result in black / white it works perfectly. I have updated the example at: http://www.cheminfo.org/?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F1cc9e892242664b1d5a37312bda159ef%2Fview.json&loadversion=true&fillsearch=Display+OCLcode+oclID
