### ISSUE TITLE
Can we make setFactorTextSize as an option for toSVG ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#57]
https://github.com/cheminfo/openchemlib-js/blob/0bacad778b4409ba07d6cb1cba511cfd1a8f6e02/src/com/actelion/research/gwt/chemlib/com/actelion/research/chem/AbstractDepictor.java#L244-L246

**Comment by lpatiny** [comment]
@targos

**Comment by targos** [comment]
OK, I added a `factorTextSize` option in version 5.5.1
