### ISSUE TITLE
full does not contains getRingSet

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#59]
Wonder if this expected.

full.pretty contains getRingSet but it seems that full does not

@targos

**Comment by targos** [comment]
I cannot reproduce:
```
> var ocl = require('openchemlib/minimal')
undefined
> var m = ocl.Molecule.fromSmiles('COC'); var r = m.getRingSet();  console.log(r.getSize())
0
undefined
> var ocl = require('openchemlib/core')
undefined
> var m = ocl.Molecule.fromSmiles('COC'); var r = m.getRingSet();  console.log(r.getSize())
0
undefined
> var ocl = require('openchemlib/full')
undefined
> var m = ocl.Molecule.fromSmiles('COC'); var r = m.getRingSet();  console.log(r.getSize())
0
undefined
```

**Comment by lpatiny** [comment]
You are right I don't understand exactly what is happening. Sometime the getRingSet collection is not available in the visualizer for a newly created molecule. I don't know why, it looks random. Could it be related that OCL is loaded by the visualizer (I render molfiles) and that there is a conflict between the 2 versions ? And if this is the case how I could prevent this ?

**Comment by targos** [comment]
Please provide a test case

**Comment by lpatiny** [comment]
https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F147099392bc0f531f02f36d39270977f%2Fview.json

The first time it will work but after it loads the other library (the one internal to the visualizer) to display the structure and after it will fail.

**Comment by targos** [comment]
Well, we cannot load more than one full version of openchemlib in the visualizer, that's expected. You shouldn't need the full one though, why don't you use `core` or `minimal`?

**Comment by lpatiny** [comment]
OK I will use core then. I just didn't know what is in full, core and min. Rings seemed to me a little 'extra' and I thought it could be only present in full.

**Comment by targos** [comment]
Minimal contains JSMolecule and everything that's in it. Full only adds the editor/displayer
