### ISSUE TITLE
drawMolecule on Retina

### ISSUE THREAD

**Issue by vnerozin** [cheminfo/openchemlib-js#60]
Hello, openchemlib team,

I am using canvas "drawMolecule" function to render molecules and have some issues on Retina. Basic approach is to set multiplied canvas size and set real size in CSS. But "drawMolecule" renders molecule on canvas always with the same physical size and just add more white space around it. Is there any solution to solve this?

**Comment by lpatiny** [comment]
In order to render molecules you can not use SVG ?
https://github.com/cheminfo/openchemlib-js/blob/master/Documentation.md#moleculetosvgwidth-height-id-options

**Comment by vnerozin** [comment]
I know about SVG and use it in some contexts also, but for this particular case I need canvas.

**Comment by lpatiny** [comment]
I'm afraid that the only way is to use canvg with the current version of openchemlib-js

https://github.com/canvg/canvg

And to transform the SVG to canvas.
