### ISSUE TITLE
dialog box validation does not trigger an update

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#62]
It is possible in the editor to specify query feature (if the molecule is a fragment) by typing the `q` key when over a bond.

However when you validate the dialog box there is no action that is trigger and the drawing is not updated. If you click after to add a bond you will see the annotation that appears.

This problem also appears when you try to edit an atom using the '? ...' button. When you validate the dialog box the structure is not refresh.

@targos Should we forward this to openchemlib java project ?

You can test it online on: https://cheminfo.github.io/openchemlib-js/dist/Editor.html

**Comment by targos** [comment]
Many thanks @rufenerc !
