### ISSUE TITLE
Copy / paste from OCL editor ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#66]
Currently OCL editor binds all the key event as far as I know.

I wonder it it would be possible to bind the copy and paste event.

https://www.w3schools.com/jsref/event_onpaste.asp

So bind to the editor 'paste' and try to convert the text content of the clipboard to a molfile.

Bind 'copy' in order to get the Molfile V3 to the clipboard would also be very practical.

This would allow to easily copy / paste molecules draws from third party program.

**Comment by rufenerc** [comment]
Implemented initial support in commit 5e3df2bd797c43cbbcf0e6a6aa844218eb9f4f31
