### ISSUE TITLE
allow new OCL.Molecule()

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/openchemlib-js#79]
It seems that previously we could directly make `new OCL.Molecule()` but this leads to an error now

Could you add default number of atoms / bonds by default ?

Today we need to specify the number of atoms and bons even if we can put 0,0.

```
const OCL=require('openchemlib');
let molecule=new OCL.Molecule(0,0);
molecule.addAtom(6);
molecule.addAtom(6);
molecule.addBond(0,1);
let smiles=molecule.toSmiles();
console.log(smiles);
```

@stropitek for info, new Molecule works if you specify the number of bonds and number of atoms

**Comment by targos** [comment]
As far as I know it was never allowed. There can be only one constructor callable from JS so I cannot add another one.

**Comment by stropitek** [comment]
In v5.5.0, it is possible to do `new OCL.Molecule()`, but not longer in v5.6.1.

There was a regression somewhere in between.

**Comment by targos** [comment]
I was an unintended breaking change introduced in https://github.com/cheminfo/openchemlib-js/commit/ce78ef69588f00f96a5d17178e6c7c3ab68a0dd1. We'll have to live with it...
