### ISSUE TITLE
Get original atom order

### ISSUE THREAD

**Issue by rbrtribeiro** [cheminfo/openchemlib-js#81]
Hi, 

I need to know the original index of all the atoms (hydrogen included) after I parse a SDF using SDFileParser. 

It seems that using getHandleHydrogenMap() is the way to go, but I couldn't figure out a way to call that before ensureHelperArrays which is called while parsing. Is this possible?

Thanks for the help, 
RR

**Comment by targos** [comment]
@rbrtribeiro You can also try to parse the SDF with that other module: https://www.npmjs.com/package/sdf-parser. And then use `openchemlib` to read the molfiles:

```js
const { molecule, map } = Molecule.fromMolfileWithAtomMap(molfile);
// map contains the original atom map
```

**Comment by targos** [comment]
I'm closing this as I think there is nothing more we can do in the library. Don't hesitate to ask if you have more questions.
