### ISSUE TITLE
A few missing return types

### ISSUE THREAD

**Issue by robertf224** [cheminfo/openchemlib-js#82]
https://github.com/cheminfo/openchemlib-js/blob/master/types.d.ts#L1425 and https://github.com/cheminfo/openchemlib-js/blob/master/types.d.ts#L3015 are missing return types (don't know enough about the library to know what those types should be)

**Comment by targos** [comment]
- `getMaxValenceUncharged` returns a `number`
- `createSVGEditor` returns a `StructureEditor`

Would you like to open a PR to fix this?

**Comment by robertf224** [comment]
sure!
