### ISSUE TITLE
Molecule sketcher buttons icons

### ISSUE THREAD

**Issue by vnerozin** [cheminfo/openchemlib-js#84]
Hi, openchemlib team,

Molecule sketcher is great feature, but I want to make integration to our platform more native. 
Is it possible to customize buttons icons in molecule sketcher?

<img width="55" alt="screen shot 2019-02-08 at 15 04 49" src="https://user-images.githubusercontent.com/10763628/52477443-f076c780-2bb2-11e9-9a59-fb82651659a9.png">

**Comment by targos** [comment]
Hi @vnerozin. At the moment there is only one possible option regarding the button icons. You can pass `true` as the second argument of the [`StructureEditor` constructor](https://cheminfo.github.io/openchemlib-js/docs/classes/structureeditor.html#constructor) or call [`createSVGEditor`](https://cheminfo.github.io/openchemlib-js/docs/classes/structureeditor.html#createsvgeditor) to have a nicer SVG toolbar.

What kind of customization are you looking for?

**Comment by vnerozin** [comment]
@targos thank you! This is much better.

But still blurred on retina. Is it possible to include "window.devicePixelRatio" on canvas rendering. 
<img width="59" alt="screen shot 2019-02-08 at 15 44 54" src="https://user-images.githubusercontent.com/10763628/52479102-8d882f00-2bb8-11e9-9735-064c0e49d288.png">

As for customization: it would be ideal to set any image for any button via css :)

**Comment by targos** [comment]
I will try the `devicePixelRatio` trick, but can't promise anything as I'm not an expert with GWT 😄

**Comment by targos** [comment]
I have a ``devicePixelRatio` of 1.5 on my laptop so at least I can test it!

**Comment by targos** [comment]
I think I have something that works, including for the rendering of the molecule. Would you mind testing it with a retina screen?
The test page is here: https://cheminfo.github.io/openchemlib-js/examples/Editor.html

**Comment by vnerozin** [comment]
It works! Thank you!

**Comment by vnerozin** [comment]
@targos how about to do the same fix for OCL.StructureView.drawMolecule?

**Comment by targos** [comment]
Honestly, I'd like to remove StructureView in a future release. We have never used it and instead focused on the [`molecule.toSVG()`](https://cheminfo.github.io/openchemlib-js/docs/classes/molecule.html#tosvg) method for rendering.
Is there anything in `StructureView` that's not possible to do with `toSVG`?

**Comment by vnerozin** [comment]
Why? I like it and use very intensively to render 100k molecules directly to canvas. toSVG is nice, but not for 100k molecules.

**Comment by vnerozin** [comment]
Also I notice that toSVG some issues to draw in small sizes, for some reasons width and height become 0 for some elements of molecule.

**Comment by lpatiny** [comment]
@vnerozin could you fill a bug report on https://github.com/Actelion/openchemlib about the width / height becoming 0 because it should be fixed and we should go towards SVG only. The quality is expected to be always perfect.

**Comment by frank-rollpin** [comment]
> Honestly, I'd like to remove StructureView in a future release. We have never used it and instead focused on the [`molecule.toSVG()`](https://cheminfo.github.io/openchemlib-js/docs/classes/molecule.html#tosvg) method for rendering.

Ouch, that would be a major inconvenience for us, as we are rendering molecules on canvas as part of canvas-rendered scene. In fact, that was the main reason for choosing openchemlib.js. @targos , can you please consider leaving that functionality intact? It's super useful and very efficient for our use cases. 
P.S.Thanks for developing the great library!

**Comment by vmarkovnikov** [comment]
I am also intensively using molecule.toSVG(), it's sad that you do not plan to support it. Please do not remove it in future releases.

**Comment by lpatiny** [comment]
It was never question about removing molecule.toSVG();

**Comment by vmarkovnikov** [comment]
@lpatiny Sorry for confusion :) I definitely meant "OCL.StructureView.drawMolecule" or toCanvas renderer.
