### ISSUE TITLE
Slow "SSSearcherWithIndex"

### ISSUE THREAD

**Issue by vmarkovnikov** [cheminfo/openchemlib-js#85]
Hello, openchemlib-js, Team!

I am implementing substructure search through 100k molecules using **SSSearcher** and **SSSearcherWithIndex**.

Did some profiling for 10k:

Following code takes **13s** per loop:
```
let ss = new SSSearcher();
let length = 10000;

let mol = molFromSmiles(smiles);
mol.setFragment(true);
ss.setFragment(mol);

for (let i = 0; i < length; i++) {
  let mol = molFromSmiles(input[i]);
  ss.setMolecule(mol);
  if (!ss.isFragmentInMolecule())
    output[i] = false;
}
```

According to documentation **SSSearcherWithIndex** should work faster, but does not.

Following code takes **75s** per first loop, and **12s** for next iterations since I do not need to calculate index (createIndex):
```
let ss = new SSSearcherWithIndex();
let length = 10000;

let mol = molFromSmiles(smiles);
mol.setFragment(true);
ss.setFragment(mol, ss.createIndex(mol));

for (let i = 0; i < length; i++) {
  let mol = molFromSmiles(input[i]);
  indexes[i] = ss.createIndex(mol);
  ss.setMolecule(mol, indexes[i]);
  if (!ss.isFragmentInMolecule())
    output[i] = false;
}
```

Am I doing something wrong? It looks like it should not work so slow...

**Comment by lpatiny** [comment]
The substructure search with index is faster to query but slower to build (need to make 512 substructure search by molecule that is being added).
The idea is therefore to precalculate the index and store them with the oclCode in the database. This is the approach that is being used in the substruture search wikipedia project:

https://github.com/cheminfo/wikipedia

You may test it by yourself directly online.
http://www.cheminfo.org/wikipedia/

**Comment by vmarkovnikov** [comment]
@lpatiny thank you!
