### ISSUE TITLE
Feature request: highlight bond rings when drawing molecule structure

### ISSUE THREAD

**Issue by kuige** [cheminfo/openchemlib-js#96]
<img width="197" alt="image" src="https://user-images.githubusercontent.com/8212800/72673557-1ab15480-3aa7-11ea-9503-a80af3ded1cc.png">

Just like this example, when drawing the molecule structure, the top bond ring is highlighted, is it possible?

The molecule drawing here is not using the editor, but calling a draw api, something like this:
`OpenChem.draw('some smiles', highlightOptions)`

**Comment by lpatiny** [comment]
you may have a look how we did it in the react-ocl component: https://zakodium.github.io/react-ocl/?path=/story/highlighting--fixed-highlight

**Comment by kuige** [comment]
@lpatiny I have checked the source of react-ocl, the highlighting job is done by the code snippet below, right ?

<img width="438" alt="image" src="https://user-images.githubusercontent.com/8212800/72705370-4828fb80-3b96-11ea-8292-de3496fac48e.png">

It is highlighted by bond id, but I want it to be highlighted by part of smiles, for example, a molecule smiles is `C1CC2(CCC3CCCC23)CC1`, I want to highlight the first part of it, `C1CC2`, the similar api should like this: `OCL.draw('C1CC2(CCC3CCCC23)CC1', { highlight: 'C1CC2' })`, then the corresponding bonds of `C1CC2` will be highlighted, without knowing the bond ids.

Is it feature possible? Or how to convert smiles to bond ids?

**Comment by targos** [comment]
I don't think we have access to the mapping from smiles elements to bond/atom ids

**Comment by kuige** [comment]
@targos Without user interaction(BondHighlightCallback), how to known the ids of highlight bonds?

For example, when page loads, I want to show user the smiles structure with some bonds highlighted, like this:

![](https://user-images.githubusercontent.com/8212800/72673557-1ab15480-3aa7-11ea-9503-a80af3ded1cc.png)

I known the smiles of the highlighted bonds, but I don't known its ids.

**Comment by targos** [comment]
Hi @thsa, maybe you know about some API of OpenChemLib that I'm not aware of?

**Comment by lpatiny** [comment]
I think OCL.Molecule.fromMolfileWithAtomMap should allow to identifiy the atoms and highlight them https://cheminfo.github.io/openchemlib-js/docs/classes/molecule.html#frommolfilewithatommap

**Comment by rufenerc** [comment]
Once you are able to determine the selected atom numbers you may use OCL.Molecule.setAtomSelection(atom,true);

**Comment by kuige** [comment]
@lpatiny @rufenerc I tried the `OCL.Molecule.fromMolfileWithAtomMap` using the following code snippet, but it throws a error, did I do it wrong ?

````
let smiles = 'CCCCC'
let molecule = OCL.Molecule.fromSmiles(smiles)
let atomMap = OCL.Molecule.fromMolfileWithAtomMap(molecule)
console.log(atomMap)
````

The error msg:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/8212800/72968024-9855c700-3dfd-11ea-90f9-c49a3ff52f65.png">

A codepen demo:
https://codepen.io/sange/pen/rNaPzPX

**Comment by lpatiny** [comment]
As you may see in the documentation I sent you
https://cheminfo.github.io/openchemlib-js/docs/classes/molecule.html#frommolfilewithatommap
It requires as parameter a text containing a molfile. You can find the specification of a molfile here: http://c4.cabrillo.edu/404/ctfile.pdf
