### ISSUE TITLE
[feature request] providing a getBondByAtomID api to get the bond between two adjacent atoms

### ISSUE THREAD

**Issue by kuige** [cheminfo/openchemlib-js#98]
Providing two atom ids, is there any method that can use to get the bond between them conveniently ?

I have checked the document , but failed to find something similar .

I can't figure out the relationship between the ids of adjacent atoms and the id of the corresponding bond. Sometimes the id of the bond between atom1(id: 10) and atom2(id: 11) is 11, but in another case, the id of the bond between atom1(id: 25) and atom2(id: 26) is 27.

For example, this smiles: `CCC(c1ccccc1)C(c1ccccc1)c1ccc(C=CC(=O)O)cc1`, 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/8212800/75088315-898e3b80-5586-11ea-94a5-cf0afdc9b5ef.png">

A codepen demo: https://codepen.io/sange/pen/bGdBYQM

Yes, I can get the target bond by iterating all the bonds and comparing the bond coordinates with the coordinates of the atoms, but I think if openchemlib can provide an api, it's much better, similar like this: `let bond = OCL.getBondByAtomID(10, 11)`

**Comment by targos** [comment]
Isn't the [getBond](https://cheminfo.github.io/openchemlib-js/docs/classes/molecule.html#getbond) method what you're looking for?

**Comment by kuige** [comment]
Oh yes, I'm looking for the `getBond` method. Thanks, targos ~
